# Generated by Django 3.2.5 on 2021-12-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_orderitem_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='shipping_product', to='store.Product'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_seller', to='store.customer'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shippingstatus',
            field=models.BooleanField(default=False),
        ),
    ]
