# Generated by Django 3.2.5 on 2021-12-14 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_auto_20211214_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
