# Generated by Django 3.2.5 on 2021-12-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_shippingaddress_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default=' ', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(default=' ', max_length=55, null=True),
        ),
    ]
