# Generated by Django 3.2.5 on 2021-12-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='orderitems',
            field=models.ManyToManyField(blank=True, related_name='shipping_item', to='store.OrderItem'),
        ),
    ]
