# Generated by Django 3.2.5 on 2021-12-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20211215_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shippingstatus',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
