# Generated by Django 3.2.5 on 2021-12-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_shippingaddress_shippingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shippingstatus',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shippingstatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
